# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execution_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateTimeField(verbose_name='date')),
                ('tester', models.CharField(max_length=100)),
                ('pass_number', models.IntegerField()),
                ('fail_number', models.IntegerField()),
                ('result', models.CharField(choices=[('PAAS', 'PAAS'), ('FAIL', 'FAIL')], default='PAAS', max_length=4)),
                ('execution_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsTestBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(max_length=3)),
                ('unit_address', models.CharField(max_length=50)),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('action', models.IntegerField()),
                ('condition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsTestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jenkinstestcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsTestSuite'),
        ),
        migrations.AddField(
            model_name='jenkinsresults',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsTestBox'),
        ),
        migrations.AddField(
            model_name='jenkinsresults',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsJob'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsProject'),
        ),
    ]
