# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_dashboard', '0002_auto_20161025_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsresults',
            name='job',
        ),
        migrations.AddField(
            model_name='jenkinsresults',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsTestCase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenkinstestsuite',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsJob'),
            preserve_default=False,
        ),
    ]
