# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_dashboard', '0003_auto_20161025_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsresults',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jenkins_dashboard.JenkinsTestBox'),
        ),
    ]
